import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {

  const [link, setLink] = useState('')
  const [slug, setSlug] = useState('')
  const [madeLink, setMadeLink] = useState('')
  const [success, setSuccess] = useState(false)
  const [error, setIsError] = useState(false)

  const createShortcut = async (slug: string, link: string) => {

    setSuccess(false)
    setIsError(false)
    setMadeLink('')

    const response = await fetch('/api/create-shortcut/', {
      method: 'POST',
      body: JSON.stringify({
        slug: slug,
        link: link
      })
    })
  
    const data = await response.json()
  
    console.log('statuscode ', data.statusCode)

    if (data.status === 200) {
      setMadeLink(slug)
      setSuccess(true)
    } else {
      setSuccess(false)
      setIsError(true)
    }

    setLink('')
    setSlug('')
  }

  return (
    <><div className={styles.container}>
      <Head>
        <title>Link shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          <a>Link</a> shortener
        </h1>

        <p className={styles.description}>
          Visit this path with an appropriate slug to visit links given to you{' '}
          <code className={styles.code}>/[slug]</code>
        </p>

        <div className={styles.grid}>
          <a className={styles.card}>
            <h2>Link &rarr;</h2>
            <input value={link} onChange={(e) => { setLink(e.target.value) } } />
          </a>

          <a className={styles.card}>
            <h2>Slug &rarr;</h2>
            <input value={slug} onChange={(e) => { setSlug(e.target.value) } } />
          </a>
        </div>
      </main>

      <div className='center'>
        <button onClick={() => createShortcut(slug, link)}>Create shortcut</button>
      </div>

      <div className="center">
        {success ? (
          <h1>
            <a href={`/${slug}`}>Successfully created link at 
            <code className={styles.code}>/{madeLink}</code>
            </a>
          </h1>) : ''}
      {error ? <h1>An error occurred. Your slug may not be unique.</h1> : ''}
    </div><footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Link shortener
        </a>
      </footer>
    </div></>
  )
}

export default Home
